name: wesh
description: Share all your best events with your friends and followers.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6
  firebase_storage: ^10.3.7
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^4.4.1+1
  firebase_dynamic_links: ^4.3.11
  firebase_messaging: ^13.1.0
  # firebase_app_check: ^0.0.7+1

  #Provider, database
  provider: ^6.0.3
  shared_preferences: ^2.0.15

  #Calendar Picker, Date formatter, Timezone
  syncfusion_flutter_calendar: ^20.2.43
  day_night_time_picker: ^1.1.2
  intl: ^0.17.0
  timeago: ^3.3.0
  # flutter_native_timezone: ^2.0.0
  localization: ^2.1.0
  csc_picker: ^0.2.6
  country_picker: ^2.0.16

  # Forms, Phone, Emails, Contacts
  intl_phone_field: ^3.1.0
  validators: ^3.0.0
  pin_code_fields: ^7.4.0
  phone_number: ^1.0.0
  form_builder_validators: ^8.3.0
  email_validator: ^2.1.17
  fast_contacts: ^1.1.1
  ussd_advanced: ^1.0.0
  telephony: ^0.2.0

  # Icons, Svg, Badges, Useful Widgets
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.1.3
  lottie: ^1.4.2
  badges: ^2.0.3
  shimmer: ^2.0.0
  another_flushbar: ^1.12.29
  liquid_progress_indicator: ^0.4.0
  auto_size_text_field: ^2.1.0

  # Media Picker, Recorder
  emoji_picker_flutter: ^1.3.1
  microphone: ^0.1.0
  just_audio: ^0.9.28
  image_picker: ^0.8.5+3
  file_picker: ^5.0.1
  video_thumbnail: ^0.5.2
  any_link_preview: ^2.0.9
  url_launcher: ^6.1.5
  video_player: ^2.4.7
  audioplayers: ^1.0.1
  record_mp3: ^3.0.0
  audio_waveforms: ^0.1.5+1
  cached_network_image: ^3.2.1
  flutter_native_image: ^0.0.6
  share_plus: ^4.0.10
  receive_sharing_intent: ^1.4.5
  screenshot: ^1.2.3
  flutter_share_me: ^1.4.0
  progressive_image: ^2.0.0
  network_to_file_image: ^4.0.1

  # Page, Scroll, ListView, Views, Story_view
  photo_view: ^0.14.0
  story_view: ^0.13.2
  introduction_screen: ^3.0.2
  swipeable_page_route: ^0.2.6
  swipe_to: ^1.0.2
  scrollable_positioned_list: ^0.3.5
  dismissible_page: ^0.7.3
  swipedetector: ^1.2.0
  visibility_detector: ^0.3.3
  grouped_list: ^5.1.2

  # Dowloader, Networks, Notifications, Background Handler
  internet_connection_checker: ^0.0.1+4
  flutter_downloader: ^1.9.1
  flutter_background_service: ^2.4.5
  flutter_isolate: ^2.0.4
  connectivity_plus: ^2.3.7
  flutter_local_notifications: ^9.7.0

  # utils
  change_app_package_name: ^1.1.0
  path: ^1.8.1
  path_provider: ^2.0.11
  flutter_screenutil: ^5.6.0
  permission_handler: ^10.2.0
  external_path: ^1.0.3
  package_info_plus: ^3.0.1
  device_information: ^0.0.4
  uuid: 3.0.6
  rxdart: ^0.27.5
  json_annotation: ^4.4.0
  age_calculator: ^1.0.0
  recase: ^4.1.0
  widget_size: ^1.0.0
  mime: ^1.0.2
  vibration: ^1.7.6
  http: ^0.13.5
  expandable_page_view: ^1.0.17
  sliding_up_panel: ^2.0.0+1
  confetti: ^0.7.0
  widget_and_text_animator: ^1.0.9
  assets_audio_player: ^3.0.6
  xid: ^1.0.12
  flutter_native_splash: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/splash.png"
  color_dark: "#383838"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/
    - assets/images/
    - assets/animations/
    - assets/images/core.assets/
    - assets/images/emoji.reactions/
    - assets/images/eventtype.icons/
    - assets/images/months.calendarscreens/
    - assets/images/useful.logos/

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri.ttf
    - family: Comic Sans MS
      fonts:
        - asset: assets/fonts/comic sans ms.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica.ttf
    - family: Moderat
      fonts:
        - asset: assets/fonts/moderat.ttf
    - family: Parnaso
      fonts:
        - asset: assets/fonts/parnaso.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Simula
      fonts:
        - asset: assets/fonts/simula.ttf
