name: wesh
description: Share all your best events with your friends and followers.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6
  firebase_storage: ^10.3.7
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^4.4.1+1
  # firebase_app_check: ^0.0.7+1

  #Provider, database
  provider: ^6.0.3
  shared_preferences: ^2.0.15

  #Calendar Picker, date formatter, Timezone
  syncfusion_flutter_calendar: ^20.2.43
  day_night_time_picker: ^1.1.2
  intl: ^0.17.0
  timeago: ^3.3.0
  # flutter_native_timezone: ^2.0.0
  localization: ^2.1.0
  csc_picker: ^0.2.6
  country_picker: ^2.0.16

  # Forms, Phone, Emails, Contacts
  intl_phone_field: ^3.1.0
  validators: ^3.0.0
  pin_code_fields: ^7.4.0
  phone_number: ^1.0.0
  form_builder_validators: ^8.3.0
  email_validator: ^2.1.17
  fast_contacts: ^1.1.1

  # Icons, Svg
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.1.3
  lottie: ^1.4.2

  # Media Picker, Recorder
  microphone: ^0.1.0
  just_audio: ^0.9.28
  chewie: ^1.3.4
  image_picker: ^0.8.5+3
  file_picker: ^5.0.1
  video_thumbnail: ^0.5.2
  any_link_preview: ^2.0.9
  url_launcher: ^6.1.5
  video_player: ^2.4.7
  audioplayers: ^1.0.1
  record_mp3: ^3.0.0
  cached_network_image: ^3.2.1

  # Views, Story_view
  photo_view: ^0.14.0
  story_view: ^0.13.2
  easy_image_viewer: ^1.1.0

  # utils
  change_app_package_name: ^1.1.0
  dio: ^4.0.6
  path: ^1.8.1
  path_provider: ^2.0.11
  uuid: 3.0.6
  xid: ^1.0.7
  rxdart: ^0.27.5
  internet_connection_checker: ^0.0.1+4

  emoji_picker_flutter: ^1.3.1
  flutter_local_notifications: ^9.7.0
  share_plus: ^4.0.10+1
  page_transition: ^2.0.9
  introduction_screen: ^3.0.2
  flutter_settings_screens: ^0.3.3-null-safety+2
  json_annotation: ^4.4.0
  badges: ^2.0.3
  connectivity_plus: ^2.3.7
  age_calculator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/musics/
    - assets/voicenotes/
    - assets/videos/
    - assets/images/months.calendarscreens/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
