import 'package:wesh/models/contact.dart';
import 'package:wesh/models/discussion.dart';
import 'package:wesh/models/event.dart';
import 'package:wesh/models/message.dart';
import 'package:wesh/models/messagestatus.dart';
import 'package:wesh/models/messagetype.dart';
import 'package:wesh/models/user.dart';
import 'package:wesh/widgets/storycard.dart';

const myId = '3';
const someoneId = '3';
final DateTime today = DateTime.now();

// User currentprofile = User(
//   id: myId,
//   email: 'royal@gmail.com',

//   facebookID: '',
//   googleID: '',
//   phone: '00242069108281',
//   country: 'CG',
//   lastStoryUpdateDateTime: DateTime(1997, 8, 22),
//   username: 'royal_g',
//   name: 'Royal GAETAN',
//   bio: 'Just a simple bio 😋 Happy to be here !',
//   profilePicture: 'assets/images/avatar 1.jpeg',
//   linkinbio: 'www.linkintr.ee/royalg',
//   birthday: DateTime(2003, 6, 16, 10),
//   events: [],
//   stories: [],
//   followers: [],
//   following: [],
//   // reminders: [Reminder(3, 0, 5), Reminder(4, 0, 5)],
//   reminders: [],
// );

// List<User> usersList = [
//   User(
//     id: '4',
//     email: 'freezz@gmail.com',
//     facebookID: '',
//     googleID: '',
//     phone: '0',
//     country: 'FR',
//     username: 'freezz',
//     name: 'Freezz Delano',
//     bio:
//         'Hava a lot to say, look at my content here for you! if you want to deal with me, pls DM me',
//     profilePicture: 'assets/images/avatar 3.jpg',
//     linkinbio: 'www.freezz.com',
//     birthday: DateTime(2004, 5, 1),
//     lastStoryUpdateDateTime: DateTime(1997, 8, 22),
//     events: [],
//     stories: [],
//     followers: [],
//     following: [],
//     // reminders: [Reminder(3, 0, 5), Reminder(4, 0, 5)],
//     reminders: [],
//   ),
//   User(
//     id: '5',
//     email: 'marcop@gmail.com',
//     facebookID: '',
//     googleID: '',
//     phone: '00242069108281',
//     country: 'UK',
//     username: 'marcos33',
//     name: 'Marco Polo',
//     bio: 'No shit to say 😎',
//     profilePicture: 'assets/images/avatar 8.jpg',
//     linkinbio: '',
//     birthday: DateTime(1990, 9, 4),
//     events: [],
//     lastStoryUpdateDateTime: DateTime(1997, 8, 22),
//     stories: [],
//     followers: [],
//     following: [],
//     // reminders: [Reminder(3, 0, 5), Reminder(4, 0, 5)],
//     reminders: [],
//   ),
//   User(
//     id: '6',
//     email: '',
//     facebookID: '',
//     googleID: '',
//     phone: '00242069108281',
//     country: 'CG',
//     username: 'kabund_0_',
//     name: 'Kabundélé Makassi',
//     bio: 'No shit to say 😎',
//     profilePicture: 'assets/images/avatar 10.jpg',
//     linkinbio: '',
//     birthday: DateTime(1997, 8, 22),
//     lastStoryUpdateDateTime: DateTime(1997, 8, 22),
//     events: [],
//     stories: [],
//     followers: [],
//     following: [],
//     // reminders: [Reminder(3, 0, 5), Reminder(4, 0, 5)],
//     reminders: [],
//   ),
// ];

List<Contact> contactsList = [
  Contact(
    phone: '',
    name: 'Frank',
    email: 'frank242@outlook.com',
    profilePicture: 'assets/images/picture 2.jpg',
    birthday: DateTime(
      2000,
      3,
      4,
    ),
  ),
  Contact(
    name: 'Claude Debor',
    email: 'claude@gmail.com',
    phone: '064992323',
    profilePicture: 'assets/images/avatar 5.jpg',
    birthday: DateTime(
      1994,
      1,
      10,
    ),
  ),
  Contact(
    email: '',
    phone: '',
    name: 'Eva V.',
    profilePicture: 'assets/images/avatar 15.jpg',
    birthday: DateTime(
      2003,
      7,
      3,
    ),
  ),
  Contact(
    email: '',
    phone: '',
    name: 'Frank',
    profilePicture: 'assets/images/avatar 7.jpg',
    birthday: DateTime(
      2000,
      8,
      8,
    ),
  ),
];

// List<Event> eventsList = [
//   Event(
//       eventId: '1',
//       uid: '1',
//       trailing: 'assets/images/emoji_pumpkin.png',
//       title: 'Sidney Party',
//       location: 'Mpaka 120, avenue de l\'independance',
//       link: 'www.soskuzab.com',
//       type: '',
//       caption: 'Fun Party, coco milk and Music',
//       color: 2,
//       createdAt: DateTime(today.year, today.month, 18, 8, 39, 19),
//       modifiedAt: DateTime(today.year, today.month, 18, 8, 39, 19),
//       startDateTime: DateTime(today.year, today.month, today.day, 14, 9, 30),
//       endDateTime: DateTime(today.year, today.month, today.day, 20, 9, 30),
//       status: 'pending'),
//   Event(
//       eventId: '2',
//       uid: '2',
//       type: '',
//       trailing: 'assets/images/emoji_beach.png',
//       title: 'Beach Concerr',
//       link: 'https//beach.com',
//       location: 'Moungali, av. KALU',
//       color: 2,
//       caption: 'Enjoy life with Dj Amarulla, on Mia Beach 🏖🎉',
//       createdAt: DateTime(today.year, today.month, 18, 8, 39, 19),
//       modifiedAt: DateTime(today.year, today.month, 18, 8, 39, 19),
//       startDateTime: DateTime(today.year, today.month, today.day, 14, 9, 30),
//       endDateTime: DateTime(today.year, today.month, today.day, 20, 9, 30),
//       status: 'pending'),
//   Event(
//       eventId: '3',
//       uid: '3',
//       trailing: 'assets/images/emoji_party.png',
//       title: 'Claude Birthday',
//       link: 'www.events.com/birthday',
//       type: '',
//       location: '',
//       color: 3,
//       caption: 'Let\'s enjoy together Claude\'s birthday 🎁🍰',
//       createdAt: DateTime(today.year, today.month, 18, 8, 39, 19),
//       modifiedAt: DateTime(today.year, today.month, 18, 8, 39, 19),
//       startDateTime: DateTime(2023, 9, 1, 10, 9, 10),
//       endDateTime: DateTime(2023, 9, 1, 22, 29, 12),
//       status: 'sent'),
// ];

// List<Discussion> discussionsList = [
//   Discussion(
//     isTyping: false,
//     profilPicture: 'assets/images/avatar 10.jpg',
//     username: 'Georges 👴',
//     lastMessage: 'Salut Royal, un joyeux anniversaire... 👋',
//     lastMessageDate: DateTime(2021, 7, 22, 6, 48, 27),
//     nbMessagesUnread: 1,
//     lastMessageType: MessageType.music,
//   ),
//   Discussion(
//     isTyping: false,
//     profilPicture: 'assets/images/avatar 3.jpg',
//     username: 'Jean Laroche',
//     lastMessage: 'Yo bro! C\'est pour ta teuf 🎈',
//     lastMessageDate: DateTime(2021, 7, 22, 22, 17, 11),
//     nbMessagesUnread: 4,
//     lastMessageType: MessageType.voicenote,
//   ),
//   Discussion(
//     isTyping: false,
//     profilPicture: 'assets/images/avatar 4.jpg',
//     username: 'Jocelyn La Vivace',
//     lastMessage: 'Heey chou, cmmt ?',
//     lastMessageDate: DateTime(2021, 7, 22, 9, 39, 54),
//     nbMessagesUnread: 2,
//     lastMessageType: MessageType.video,
//   ),
//   Discussion(
//     isTyping: false,
//     profilPicture: 'assets/images/avatar 5.jpg',
//     username: 'Didier Vincent',
//     lastMessage: 'Je t\'ai envoyé un cadeau bro',
//     lastMessageDate: DateTime(2021, 7, 22, 10, 13, 34),
//     nbMessagesUnread: 20,
//     lastMessageType: MessageType.gift,
//   ),
//   Discussion(
//     isTyping: false,
//     profilPicture: 'assets/images/avatar 6.jpg',
//     username: 'Zizus Capotus',
//     lastMessage: 'Man t\'es un fou...',
//     lastMessageDate: DateTime(2021, 7, 22, 12, 33, 49),
//     nbMessagesUnread: 7,
//     lastMessageType: MessageType.image,
//   ),
//   Discussion(
//     isTyping: true,
//     profilPicture: 'assets/images/avatar 7.jpg',
//     username: 'Elvira C.',
//     lastMessage: 'houlala houlala',
//     lastMessageDate: DateTime(2021, 8, 12, 08, 20, 10),
//     nbMessagesUnread: 2,
//     lastMessageType: MessageType.text,
//   ),
//   Discussion(
//     isTyping: false,
//     profilPicture: 'assets/images/avatar 15.jpg',
//     username: 'Emiliana',
//     lastMessage: '10.000FCFA pour toi mon Royal 🥰',
//     lastMessageDate: DateTime(2021, 7, 22, 19, 33, 30),
//     nbMessagesUnread: 1,
//     lastMessageType: MessageType.payment,
//   ),
//   Discussion(
//     isTyping: false,
//     profilPicture: 'assets/images/avatar 9.jpg',
//     username: 'Eva Mendes',
//     lastMessage: 'C\'est bizarre que tu soies né aujourd\'hui',
//     lastMessageDate: DateTime(2021, 7, 22, 7, 33, 30),
//     nbMessagesUnread: 1,
//     lastMessageType: MessageType.none,
//   ),
// ];

// List<Message> messagesList = [
//   Message(
//     messageId: 'fflkr',
//     id: 1,
//     senderId: someoneId,
//     receiverId: myId,
//     createdAt: DateTime(2022, 8, 12, 9, 20, 27),
//     status: '${MessageStatus.doubleticks}',
//     type: '${MessageType.text}',
//     data: '',
//     caption: 'Salut bro, comment tu vas?',
//   ),
//   Message(
//     messageId: 'fflkr',
//     id: 2,
//     senderId: myId,
//     receiverId: someoneId,
//     createdAt: DateTime(2022, 8, 12, 10, 34, 11),
//     status: '${MessageStatus.doubleticks}',
//     type: '${MessageType.text}',
//     data: '',
//     caption: 'Wesh! 👋 bien, et toi',
//   ),
//   Message(
//     messageId: 'fflkr',
//     id: 3,
//     senderId: myId,
//     receiverId: someoneId,
//     createdAt: DateTime(2022, 8, 12, 10, 20, 19),
//     status: '${MessageStatus.seen}',
//     type: '${MessageType.text}',
//     data: '',
//     caption: 'Envoie moi les videos et images dont tu me parlais hier 🙂',
//   ),
//   Message(
//     messageId: 'fflkr',
//     id: 4,
//     senderId: someoneId,
//     receiverId: myId,
//     createdAt: DateTime(2022, 8, 12, 14, 12, 39),
//     status: '${MessageStatus.seen}',
//     type: '${MessageType.image}',
//     data: 'assets/images/picture 1.jpg',
//     caption:
//         '🔥😎 Check cette image, trop top, je t\'assure. Quand je l\'ai prise, j\'avais le seum de capturer une belle image. Et voilà le travail 👆👆',
//   ),
//   Message(
//     messageId: 'fflkr',
//     id: 5,
//     senderId: myId,
//     receiverId: someoneId,
//     createdAt: DateTime(2022, 8, 12, 15, 13, 14),
//     status: '${MessageStatus.sent}',
//     type: '${MessageType.video}',
//     data: 'assets/videos/video 4.mp4',
//     caption: 'Voici une video que j\'ai énormement aimée',
//   ),
//   Message(
//     messageId: 'fflkr',
//     id: 6,
//     senderId: someoneId,
//     receiverId: myId,
//     createdAt: DateTime(2022, 8, 12, 16, 30, 12),
//     status: '${MessageStatus.sent}',
//     type: '${MessageType.music}',
//     data: 'assets/musics/L\'ame dans l\'eau.mp3',
//     caption:
//         'Mylène Famer, la meilleure de sa génération 👌 Je te la recommande fortement',
//   ),
//   Message(
//     messageId: 'fflkr',
//     id: 7,
//     senderId: myId,
//     receiverId: someoneId,
//     createdAt: DateTime(2022, 8, 12, 14, 13, 41),
//     status: '${MessageStatus.pending}',
//     type: '${MessageType.voicenote}',
//     data: '',
//     caption: '',
//   ),
// ];

List<StoryCard> storiesList = [
  // StoryCard(
  //   profilePicture: 'assets/images/avatar 10.jpg',
  //   username: 'Kipokolo Kabundelé',
  //   lastStoryTime: DateTime.now(),
  //   type: 'unread',
  // ),
  // StoryCard(
  //   profilePicture: 'assets/images/avatar 4.jpg',
  //   username: 'Lay Claura',
  //   lastStoryTime: DateTime.now(),
  //   type: 'unread',
  // ),
  // StoryCard(
  //   profilePicture: 'assets/images/avatar 15.jpg',
  //   username: 'Eva Mendes',
  //   lastStoryTime: DateTime.now(),
  //   type: 'unread',
  // ),
];

List<StoryCard> storiesSeenList = [
  // StoryCard(
  //   profilePicture: 'assets/images/avatar 13.jpg',
  //   username: 'Vanessa Lau',
  //   lastStoryTime: DateTime.now(),
  //   type: 'seen',
  // ),
  // StoryCard(
  //   profilePicture: 'assets/images/avatar 7.jpg',
  //   username: 'Claude RR',
  //   lastStoryTime: DateTime.now(),
  //   type: 'seen',
  // ),
];
